#! /bin/bash

echo
echo Updating old server config files
echo

rm /Solace AI Server Project/Solace AI Server Source Code/Settings/worldserver.conf
rm /Solace AI Server Project/Solace AI Server Source Code/settings/authserver.conf
rm /Solace AI Server Project/Solace AI Server Source Code/Settings/bots.conf

cp /Solace AI Server Project/Solace AI Server Source Code/src/server/worldserver/worldserver.conf.dist /Solace AI Server Project/Solace AI Server Source Code/worldserver.conf
cp /Solace AI Server Project/Solace AI Server Source Code/src/server/authserver/authserver.conf.dist /Solace AI Server Project/Solace AI Server Source Code
cp /Solace AI Server Project/Solace AI Server Source Code/src/plugins/playerbot/aiplayerbot.conf.dist.in /Solace AI Server Project/Solace AI Server Source Code