#! /bin/bash

cd /Solace AI Server Project/Solace AI Server Source Code
chmod +x ./update
chmod +x ./update.sh
chmod +x ./compile.sh
chmod +x ./rebuild
chmod +x ./rebuild.sh
chmod +x ./update-config
./update.sh
cd ~